# Generated by Django 5.2.6 on 2025-11-14 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketSchedule",
            fields=[
                (
                    "ScheduleID",
                    models.BigAutoField(
                        db_column="ScheduleID", primary_key=True, serialize=False
                    ),
                ),
                ("status", models.CharField(db_column="Status", max_length=10)),
                ("open_hour", models.IntegerField(db_column="OpenHour")),
                ("open_minute", models.IntegerField(db_column="OpenMinute")),
                ("close_hour", models.IntegerField(db_column="CloseHour")),
                ("close_minute", models.IntegerField(db_column="CloseMinute")),
                ("holiday", models.BooleanField(db_column="Holiday", default=False)),
            ],
            options={
                "db_table": "MarketSchedule",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "StockID",
                    models.BigAutoField(
                        db_column="StockID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "ticker",
                    models.CharField(db_column="Ticker", max_length=10, unique=True),
                ),
                ("name", models.CharField(db_column="CompanyName", max_length=100)),
                (
                    "initial_price",
                    models.DecimalField(
                        db_column="InitialPrice", decimal_places=2, max_digits=12
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        db_column="CurrentPrice", decimal_places=2, max_digits=12
                    ),
                ),
                (
                    "opening_price",
                    models.DecimalField(
                        db_column="OpeningPrice", decimal_places=2, max_digits=12
                    ),
                ),
                (
                    "day_high",
                    models.DecimalField(
                        db_column="DayHigh", decimal_places=2, max_digits=12
                    ),
                ),
                (
                    "day_low",
                    models.DecimalField(
                        db_column="DayLow", decimal_places=2, max_digits=12
                    ),
                ),
                ("float_shares", models.BigIntegerField(db_column="FloatShares")),
            ],
            options={
                "db_table": "Stock",
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "UserID",
                    models.BigAutoField(
                        db_column="UserID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "FullName",
                    models.CharField(
                        blank=True, db_column="FullName", max_length=100, null=True
                    ),
                ),
                (
                    "UserName",
                    models.CharField(db_column="UserName", max_length=50, unique=True),
                ),
                (
                    "email",
                    models.EmailField(db_column="Email", max_length=100, unique=True),
                ),
                (
                    "password",
                    models.CharField(db_column="PasswordHash", max_length=255),
                ),
                (
                    "Role",
                    models.CharField(
                        db_column="Role", default="CUSTOMER", max_length=20
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "User",
            },
        ),
        migrations.CreateModel(
            name="BrokerageAccount",
            fields=[
                (
                    "AccountID",
                    models.BigAutoField(
                        db_column="AccountID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "cash_balance",
                    models.DecimalField(
                        db_column="Balance", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="UserID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "BrokerageAccount",
            },
        ),
        migrations.CreateModel(
            name="PriceTick",
            fields=[
                (
                    "TickID",
                    models.BigAutoField(
                        db_column="TickID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, db_column="Timestamp"),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_column="Price", decimal_places=2, max_digits=12
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        db_column="StockID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_ticks",
                        to="customer.stock",
                    ),
                ),
            ],
            options={
                "db_table": "PriceTick",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "OrderID",
                    models.BigAutoField(
                        db_column="OrderID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        db_column="Action",
                        max_length=10,
                    ),
                ),
                ("quantity", models.BigIntegerField(db_column="Quantity")),
                ("status", models.CharField(db_column="Status", max_length=20)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "executed_at",
                    models.DateTimeField(blank=True, db_column="ExecutedAt", null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        db_column="AccountID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="customer.brokerageaccount",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        db_column="StockID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.stock",
                    ),
                ),
            ],
            options={
                "db_table": "Order",
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "TradeID",
                    models.BigAutoField(
                        db_column="TradeID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "executed_price",
                    models.DecimalField(
                        db_column="ExecutedPrice", decimal_places=2, max_digits=12
                    ),
                ),
                ("executed_qty", models.BigIntegerField(db_column="ExecutedQty")),
                (
                    "executed_time",
                    models.DateTimeField(auto_now_add=True, db_column="ExecutedTime"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="OrderID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="customer.order",
                    ),
                ),
            ],
            options={
                "db_table": "Trade",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "TransactionID",
                    models.BigAutoField(
                        db_column="TransactionID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAW", "Withdraw"),
                            ("STOCK_TRADE", "Stock Trade"),
                        ],
                        db_column="TransType",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_column="Amount", decimal_places=2, max_digits=12
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        db_column="AccountID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="customer.brokerageaccount",
                    ),
                ),
            ],
            options={
                "db_table": "Transaction",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "PositionID",
                    models.BigAutoField(
                        db_column="PositionID", primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.BigIntegerField(db_column="Quantity")),
                (
                    "account",
                    models.ForeignKey(
                        db_column="AccountID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="customer.brokerageaccount",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        db_column="StockID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.stock",
                    ),
                ),
            ],
            options={
                "db_table": "Position",
                "unique_together": {("account", "stock")},
            },
        ),
    ]
